### ISSUE TITLE
CMake error after recent update

### ISSUE THREAD

**Issue by stellaraccident** [llvm/mlir-npcomp#11]
https://buildkite.com/iree/mlir-npcomp-standalone/builds/27#6fba062f-0357-4195-9d16-4daa9f651d75

CMake Error at /work/install/llvm-project/mlir-generic-rtti/lib/cmake/mlir/AddMLIR.cmake:187 (get_target_property):
--
  | INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  | property "LINK_LIBRARIES" is not allowed.
  | Call Stack (most recent call first):
  | /work/install/llvm-project/mlir-generic-rtti/lib/cmake/mlir/AddMLIR.cmake:213 (mlir_check_link_libraries)
  | lib/Python/CMakeLists.txt:54 (mlir_check_all_link_libraries)

**Comment by stellaraccident** [comment]
@stephenneuendorffer 

I can look at this - just noting the failure for you.

**Comment by stephenneuendorffer** [comment]
Sorry, thought I had fixed that.

**Comment by stephenneuendorffer** [comment]
It's a quick fix, but it will take me an hour or so to fix it.

**Comment by stellaraccident** [comment]
Thanks - no hurry. I think it's just you and me right now, and I'm busy on other things.

**Comment by stephenneuendorffer** [comment]
FYI, the fix is in, but the buildkite server seems to be having issues.  Maybe disk full?

**Comment by stellaraccident** [comment]
Indeed. Thanks for the fix. I'll check on the server tmw.
