### ISSUE TITLE
 ninja check-npcomp failed

### ISSUE THREAD

**Issue by xuanhuo** [llvm/mlir-npcomp#154]
when I run  ninja check-npcomp, there are some erros : 

Testing Time: 2.29s
  Unsupported:  1
  Passed     :  2
  Failed     : 74
FAILED: test/CMakeFiles/check-npcomp-lit

why?

**Comment by mikeurbach** [comment]
Hi @xuanhuo, can you provide some more details about how you are setting up the project? Are you using the steps from here https://github.com/llvm/mlir-npcomp#build-instructions, using the Docker container, etc.?

**Comment by xuanhuo** [comment]
Thank you @mikeurbach, I didn't use Docker, just used command from “Vanilla - numpy-only, no pytorch”

**Comment by xuanhuo** [comment]
@mikeurbach I'd like to docker pull stellaraccident/npcomp:build-pytorch-1.3, I found it's very very slow

**Comment by mikeurbach** [comment]
@xuanhuo If you can, I think using the docker image will be the easiest way to have a consistent build environment.

However, if you want to use the setup from "Vanilla - numpy-only, no pytorch", it should work. In order to help, we'd need more information about your development environment: what OS version, what CC/CXX compiler version, whether CMake reported any errors when you ran `./build_tools/cmake_configure.sh`, and what were the test failures?

I can't promise I can help you get to the bottom of it, but I did recently change some of the CMake settings, and I want to make sure those changes are not the root of your issues.

**Comment by xuanhuo** [comment]
@mikeurbach I'd like to use setup from "Vanilla - numpy-only, no pytorch" because I have failed to download the docker image maybe the network is not stable.
my development environment as below：
OS version ： Ubuntu 18.04
CC/CXX version : 7.5
There's not any errors when I ran./build_tools/cmake_configure.sh
There are many errors when I ran ninja check-npcomp
root@R6S1:/home/wda/2021/mlir-npcomp/build# ninja check-npcomp
[1/2] Running the npcomp regression tests
FAIL: NPCOMP_OPT :: CAPI/ir.c (2 of 77)
******************** TEST 'NPCOMP_OPT :: CAPI/ir.c' FAILED ********************
Script:
--
: 'RUN: at line 10';   /home/wda/2021/mlir-npcomp/build/bin/npcomp-capi-ir-test 2>&1 | /home/wda/2021/mlir-npcomp/build/install-mlir/bin/FileCheck /home/wda/2021/mlir-npcomp/test/CAPI/ir.c
--
Exit Code: 1

Command Output (stderr):
--
/home/wda/2021/mlir-npcomp/test/CAPI/ir.c:57:18: error: CHECK-LABEL: expected string not found in input
 // CHECK-LABEL: @types
                 ^
<stdin>:1:1: note: scanning from here
LLVM ERROR: a dialect with namespace 'tensor' has already been registered
^
<stdin>:1:68: note: possible intended match here
LLVM ERROR: a dialect with namespace 'tensor' has already been registered

**Comment by mikeurbach** [comment]
@xuanhuo I tried to reproduce these errors with a fresh download of mlir-npcomp, following those same instructions. I didn't encounter the same issue. My setup:

```
OS: Ubuntu 18.04
CC: Ubuntu clang version 11.0.1-++20201218093139+43ff75f2c3fe-1~exp1~20201218203800.157
CXX: Ubuntu clang version 11.0.1-++20201218093139+43ff75f2c3fe-1~exp1~20201218203800.157
```

As you can see, I am using clang version 11.0.1 from last December. When you say your CC/CXX version is 7.5, do you mean clang or gcc? The instructions make it seem like the supported CC/CXX is clang-10 here: https://github.com/llvm/mlir-npcomp/blob/main/README.md#common-prep, and I have only used clang-9, clang-10, and clang-11 in the time I have been building this project.

**Comment by xuanhuo** [comment]
@mikeurbach thank you very much, I misunderstood what you mean. I used CC/C++ is clang 10.0.0. I downloand clang from https://releases.llvm.org/download.html and it's the Pre-Built Binaries.
I have one question about` export LDFLAGS=-fuse-ld=$(which ld.lld-$LLVM_VERSION)` 
If I used clang-10.0.0, there is no ld.lld-10.0.0, there is just ld.lld. so I have changed ` export LDFLAGS=-fuse-ld=$(which ld.lld-$LLVM_VERSION)`  to ` export LDFLAGS=-fuse-ld=$(which ld.lld)`, I think it don't cause any impact. 
So Did I do something wrong?

**Comment by stellaraccident** [comment]
> LLVM ERROR: a dialect with namespace 'tensor' has already been

This is a symptom of the `TypeID` dynamic linking odr violation issue, and basically another indication that the libMLIR machinery does not work. I should change npcomp to just use BUILD_SHARED_LIBS mode until we can fix it more appropriately -- although we have anther bug report on macos that that is broken as well. I will need to spend some time staring at this tomorrow. It is concerning that this is meta stable on Linux.

Also, the use of lld is optional: it can improve link time but is not required for correctness.

**Comment by xuanhuo** [comment]
@stellaraccident Thank you very much

**Comment by xuanhuo** [comment]
> > LLVM ERROR: a dialect with namespace 'tensor' has already been
> 
> This is a symptom of the `TypeID` dynamic linking odr violation issue, and basically another indication that the libMLIR machinery does not work. I should change npcomp to just use BUILD_SHARED_LIBS mode until we can fix it more appropriately -- although we have anther bug report on macos that that is broken as well. I will need to spend some time staring at this tomorrow. It is concerning that this is meta stable on Linux.
> 
> Also, the use of lld is optional: it can improve link time but is not required for correctness.

Did you have fixed it?

**Comment by stellaraccident** [comment]
I have not yet been able to repro this issue. Can you provide more details about your operating system and installed software?

**Comment by amaleewilson** [comment]
I'm getting the same errors. 

```
$ ninja check-npcomp
[1/2] Running utility command for NPCOMPPythonResources
[1/2] Running the npcomp regression tests
-- Testing: 104 tests, 12 workers --
Testing:
FAIL: NPCOMP_OPT :: Python/Compiler/Numpy/ufunc.py (1 of 104)
******************** TEST 'NPCOMP_OPT :: Python/Compiler/Numpy/ufunc.py' FAILED ********************
Script:
--
: 'RUN: at line 1';   /Library/Developer/CommandLineTools/usr/bin/python3 /Users/wils220/mlir-npcomp/test/Python/Compiler/Numpy/ufunc.py | /Users/wils220/mlir-npcomp/build/bin/npcomp-opt -split-input-file | /Users/wils220/mlir-npcomp/build/install-mlir/bin/FileCheck /Users/wils220/mlir-npcomp/test/Python/Compiler/Numpy/ufunc.py --dump-input=fail
--
Exit Code: 1

Command Output (stderr):
--
LLVM ERROR: a dialect with namespace 'std' has already been registered
/Users/wils220/mlir-npcomp/test/Python/Compiler/Numpy/ufunc.py:18:16: error: CHECK-LABEL: expected string not found in input
# CHECK-LABEL: func @global_add
               ^
```

Followed the build directions exactly. On macOS Catalina. Tried using Apple clang, also tried building clang and libcxx with mlir and using those. Same issue no matter how I do it. Any idea how to fix this?

**Comment by stellaraccident** [comment]
I believe we finally have a comprehensive fix for this issue ready to land. It is in two parts:

* Upstream: https://reviews.llvm.org/D106520
* npcomp: https://github.com/llvm/mlir-npcomp/pull/251

Fixing this completely required a complete re-engineering of the way that the upstream C/Python API builds were done and is rather involved. Hoping to land the upstream change tomorrow, and then will rework the npcomp CI and land the change locally.

Thanks for your patience. This was hard.

**Comment by stellaraccident** [comment]
The root issue reported here has been fixed at head. There are a couple of other downstream issues for MacOS that I am fixing separately (it never got this far before and they were latent). Closing this one and continuing on #254.
