### ISSUE TITLE
Make required PyTorch version clear

### ISSUE THREAD

**Issue by ryotatomioka** [llvm/mlir-npcomp#164]
With PyTorch nightly (1.9.0.dev20210216) installed via conda, I get the following error
```
static_assert(c10::guts::false_t<Func>(), ".impl_UNBOXED(...) was removed. Please use .impl(...) instead.");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~
../frontends/pytorch/csrc/builder/acap_dispatch.cpp:596:5: note: in instantiation of function template specialization 'torch::Library::impl_UNBOXED<const char *, at::Tensor (const at::Tensor &, const at::Tensor &, const c10::optional<at::Tensor> &, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)>' requested here
  m.impl_UNBOXED("convolution", &AcapController::convolutionKernel);
```

I could do a bisection but it would be better if you could point me to a version that is known to work. Thank you!

**Comment by byronyi** [comment]
Is this fixed in #158?

**Comment by raikonenfnu** [comment]
Looks like this error shouldn't appear after that, because https://github.com/llvm/mlir-npcomp/pull/158/files
actually change  "m.impl_UNBOXED("convolution", &AcapController::convolutionKernel);" to m.impl(("convolution", &AcapController::convolutionKernel);
@ryotatomioka Can you try with top of master?

**Comment by ryotatomioka** [comment]
@byronyi yes thanks the issue is resolved.

**Comment by ryotatomioka** [comment]
@raikonenfnu this message seems to be outdated?
https://github.com/llvm/mlir-npcomp/blob/c424c24ed8330483ebe91fe7f1001e57243e3561/frontends/pytorch/csrc/builder/acap_dispatch.cpp#L197
