### ISSUE TITLE
Convert ATen.td to  "let results =" style

### ISSUE THREAD

**Issue by stephenneuendorffer** [llvm/mlir-npcomp#17]
We generally prefer the "let results =" style vs Results inheritance, especially since you use the let-form for arguments.

Since the form you have it in seems consistent through the file, let's not change now. We can do a cleanup to the let form in a followup if desired.

_Originally posted by @stellaraccident in https://github.com/llvm/mlir-npcomp/pull/16_

**Comment by silvasean** [comment]
New ATen dialect generator does this. Closing.
