### ISSUE TITLE
Use `BUILD_SHARED_LIBS` instead of `LLVM_BUILD_LLVM_DYLIB`

### ISSUE THREAD

**Issue by stellaraccident** [llvm/mlir-npcomp#189]
On https://github.com/llvm/circt/pull/767, they were experiencing some of the same issues we have intermittently observed with respect to effects of `TypeID` multiple definition issues resulting in equality of types being dependent on which shared library does the check.

It is my belief that the way that `libLLVM.so`/`libMLIR.so`/`libNPCOMP.so` are "over-linked" (and order inverted on the link command line) creates the conditions for this kind of issue to surface (although, I have not actually managed to ever nail it down to a specific smoking gun -- more of a "that is clearly not the right way to do it and would result in this kind of issue easily" kind of judgments).

I suggested that @mikeurbach try to use `BUILD_SHARED_LIBS` mode because it gets the shared-library layering correctly, and this resolved the mismatch for them. I suggest we switch npcomp to the same regime and remove support for linking against `libMLIR.so`. I am very slowly trying to complete https://reviews.llvm.org/D94387, which should fix the situation for the aggregate dylib linking modes, which would be nice for an eventual production release. In that new world, the dylib building mode is a specialization of `BUILD_SHARED_LIBS`, so we would need to switch locally regardless.

**Comment by stellaraccident** [comment]
I suspect this would also fix issues like this one, which we have not been able to track down: https://github.com/llvm/mlir-npcomp/issues/154

**Comment by mikeurbach** [comment]
FYI I tried making this change just for grins, and found there were a few places where the linker was missing symbols. At the very least, this will require making sure the libraries are all linked appropriately in CMake. In our experience with CIRCT, once missing (and potentially circular) dependencies are resolved in CMake, the BUILD_SHARED_LIBS option should just work:tm:

I don't have time to look into it right now, but if no one else picks this up in the meantime, I can help out with this.

**Comment by mikeurbach** [comment]
FYI I took this plunge last night.. Should have a PR today.

**Comment by stephenneuendorffer** [comment]
I also tend to link with libLLVM.so, but end up statically linking MLIR because libMLIR.so is challenging to use.   I'm a little concerned that BUILD_SHARED_LIBS isn't the right way to go either for deployment scenarios (at least with the current structure) because there are so many shared libraries, and hence shared-library boundaries.  The real key with all of the TypeID problems is that there needs to be a good way to move back and forth with dependencies on libraries like MLIRSupport automatically being converted to a link against libMLIR.so.  This machinery existsfor LLVM, but hasn't been replicated for MLIR.

**Comment by mikeurbach** [comment]
I use BUILD_SHARED_LIBS, and made the PR above to show how I needed to update npcomp to enable that.

If we don't want to switch from BUILD/LINK_DYLIB to BUILD_SHARED_LIBS, I think I can at least keep the addional dependencies in the first commit of that PR, and only link in libMLIR when the flag is set to build it. That should allow npcomp to keep using the DYLIB flags as the recommended/tested approach, but BUILD_SHARED_LIBS should at least become possible.

**Comment by stellaraccident** [comment]
I would just switch to `BUILD_SHARED_LIBS` exclusively and trust that we can come up with a more supportable way to build an aggregate shared library before needing to hard block on this. I'm more concerned that the more I dig into libLLVM/libMLIR the more I find that it is UB waiting to happen (and often, actually happening). The way that it overlinks by linking to the shared library first (violation of how linking should work and explicitly disallowed by some Linux configs with more modern settings) and then just "filling in" with additional static linkage is not right. `BUILD_SHARED_LIBS` is closer to where we need to be ultimately with some of the libraries being expanded into aggregates.

I've been really tired and pandemic overwhelmed, but would like to get back to fixing the `BUILD_SHARED_LIBS` situation upstream. I don't trust what is there now for libLLVM/libMLIR at all -- it accidentally works at best.

(also, the other thing that cuts us and creates these "TypeID" problems is vagaries in the RPATH mechanism, which interplays badly with mixed RTLD_LOCAL vs RTLD_GLOBAL loading, which tends to come up in (Python) extension loading scenarios)

**Comment by mikeurbach** [comment]
> I would just switch to BUILD_SHARED_LIBS exclusively

In this case, I believe this is implemented in the linked PR. I'll request both of you as reviewers and we can hash it out over there.

**Comment by stellaraccident** [comment]
We're now using the new build setup with completely static/hidden linkage.
