### ISSUE TITLE
Building in the docker container: ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by amaliujia** [llvm/mlir-npcomp#192]
I have followed the instruction:
1. Setup docker container [1]. Done
2. In docker container, do Command prep [2]. Done and without a problem.
3. Try either vanilla compile or PyTorch Frontend compile, running `./build_tools/cmake_configure.sh` is fine. But then both give me:

`ninja: error: loading 'build.ninja': No such file or directory`

Do you have a recommendation how does this ninja error can get fixed?

[1]: https://github.com/llvm/mlir-npcomp#start-a-docker-dev-container-based-on-our-image
[2]: https://github.com/llvm/mlir-npcomp#start-a-docker-dev-container-based-on-our-image

**Comment by amaliujia** [comment]
cc @stellaraccident 

Hi Stella,

Can you give a suggestion?

**Comment by silvasean** [comment]
Do you have a log you can share? That would help debug this. It seems like maybe CMake failed.

**Comment by amaliujia** [comment]
@silvasean thanks. Let me re-produce locally and share whatever log I can find

**Comment by amaliujia** [comment]
I figured out offline.

So for docker env I should use `--build /build/npcomp` to which cmake_configure.sh writing build files. However I actually used `--build build` which should be used in non-docker env.

Thanks @silvasean for your help anyway!
