### ISSUE TITLE
Trailing for "add_" not working

### ISSUE THREAD

**Issue by raikonenfnu** [llvm/mlir-npcomp#195]
Hey guys,

I tried updating to this [patch](https://github.com/llvm/mlir-npcomp/commit/703428eff42310714878f331442e6e912d1fe461)
but when I tried tracing with acap_dispatch, it seems to still be using "add" instead of "add_". I have a small unit test and the output that is generated as attachment
[add_test.zip](https://github.com/llvm/mlir-npcomp/files/6173279/add_test.zip)
. Any help/comments would be appreciated! :)

**Comment by silvasean** [comment]
That's an artifact of how pytorch runs the code. It's not something we have control over. In this case, they use the "out" param version of add (4 operand) instead of the "inplace" (add_) aten kernel.
