### ISSUE TITLE
From _torch_mlir import _get_mlir ERROR

### ISSUE THREAD

**Issue by alphaRGB** [llvm/mlir-npcomp#196]
I have successfully build the llvm, mlir , and pytorch front, generate the  _mlir and _torch_mlir *.so file.  And I have add thems into PATHPYTHON .   But when I test, there exist some error:

Import Error
```
 import npcomp.frontends.pytorch as torch_mlir
  File "mlir-npcomp/build/python/npcomp/frontends/pytorch/__init__.py", line 8, in <module>
    from _torch_mlir import _get_mlir
ImportError: cannot import name '_get_mlir' from '_torch_mlir' (mlir-npcomp/build/python/_torch_mlir.cpython-37m-x86_64-linux-gnu.so)
```

The `_torch_mlir` module can be import successfully in python,  I have test `help(_torch_mlir)`  and `type(_torch_mlir) `in python, but the printed result not found `_get_mlir` function.

code
```
import npcomp.frontends.pytorch as torch_mlir

dev = torch_mlir.mlir_device()
t0 = torch.randn((4,4), device=dev)
t1 = torch.randn((4,4)).to(dev)
t2 = t0 + t1
t2_mlir = torch_mlir.get_mlir( t2 )
t2_cpu = t2.to('cpu')

```

**Comment by alphaRGB** [comment]
> Docs were out of date. Just updated them: [b0ac040](https://github.com/llvm/mlir-npcomp/commit/b0ac04001db4aef4d8e6b96d2b720fae6b02d03c)

Thank you, This can be run.   I have a question that why the data type of torch-mlir is represented as np.ndarray, not tensor<x x x f32> directly ?

**Comment by silvasean** [comment]
Tensor is not mutable.
