### ISSUE TITLE
No module named 'torch_mlir'

### ISSUE THREAD

**Issue by hunbssfy** [llvm/mlir-npcomp#244]
Hello!

I am just trying to go through build instructions in the README. I built Pytorch Frontend in docker container following the instructions and then installed IREE via pip3 install. But When I try to run the e2e test targeting the IREE backend I got the following error:
```
root@0e8aafd709c6:/src/mlir-npcomp# python frontends/pytorch/e2e_testing/torchscript/main.py --config=iree
Traceback (most recent call last):
  File "frontends/pytorch/e2e_testing/torchscript/main.py", line 9, in <module>
    from torch_mlir.torchscript.e2e_test.framework import run_tests
ModuleNotFoundError: No module named 'torch_mlir'
```
Could anyone help me? I think I didn't miss any instructions in the README...

**Comment by byronyi** [comment]
You need to set the env variables in `.env`.

**Comment by hunbssfy** [comment]
> You need to set the env variables in `.env`.

Hey byronyi,

Could you elaborate a little? my .env file is like this rn:

![image](https://user-images.githubusercontent.com/6930027/124227980-10b9cf00-db3e-11eb-81e8-96a36d0116ca.png)

**Comment by hunbssfy** [comment]
And Do I need to run this 'Vanilla NumPy-only build' step:
![image](https://user-images.githubusercontent.com/6930027/124230796-11ecfb00-db42-11eb-9f12-c643f018d56e.png)
If I do, I don't think the ninja command works because there is no ninja file generated from the configuration step, I got this error:
![image](https://user-images.githubusercontent.com/6930027/124230933-3ba62200-db42-11eb-88e2-e732bb1e9a85.png)

**Comment by silvasean** [comment]
Hi @hunbssfy , can you try using `tools/torchscript_e2e_test.sh` -- I recently changed the invocation method to that from a raw python invocation.

I fixed the docs here: https://github.com/llvm/mlir-npcomp/commit/c289d83407951e6d8ec654ebbafb3e4c6e4202f9

**Comment by hunbssfy** [comment]
> Hi @hunbssfy , can you try using `tools/torchscript_e2e_test.sh` -- I recently changed the invocation method to that from a raw python invocation.
> 
> I fixed the docs here: [c289d83](https://github.com/llvm/mlir-npcomp/commit/c289d83407951e6d8ec654ebbafb3e4c6e4202f9)

Hello @silvasean, I tried using `tools/torchscript_e2e_test.sh` but it still gives the same error:

![image](https://user-images.githubusercontent.com/6930027/124411441-1f42f900-dd7f-11eb-86a9-b15f5c79ee7a.png)

**Comment by hunbssfy** [comment]
Relly need some help here to get this test running. Anyone could help me a little?

**Comment by stellaraccident** [comment]
It looks like the PYTHONPATH env variable is not set (just having it in the .env file doesn't do anything for your shell). Try exporting that in a way that is convenient.

(Sorry for delays - several of us who work on this are on vacation and afk)

**Comment by hunbssfy** [comment]
> It looks like the PYTHONPATH env variable is not set (just having it in the .env file doesn't do anything for your shell). Try exporting that in a way that is convenient.
> 
> (Sorry for delays - several of us who work on this are on vacation and afk)

Hello stellaraccident:

Thanks for the reply! I think my PYTHONPATH env variable is set to the directory containing the built python package (torch-mlir), here is it:
![image](https://user-images.githubusercontent.com/6930027/124706482-f01cbb00-df29-11eb-9a66-c141a2a3707e.png)

And here is what's under the directory of `/build/npcomp/python/`. Am I setting the correct PYTHONPATH?

**Comment by hunbssfy** [comment]
Hi stellaraccident,

Well I added `torch_mlir` and `mlir` 's import path to the sys.path in main.py manually under e2e_testing, and it worked. Here are the test results I got:
![image](https://user-images.githubusercontent.com/6930027/124712875-6b826a80-df32-11eb-855d-b994e033f521.png)
Is this normal? And what does Expectedly Failed mean?
And the strange thing is I still cannot import torch_mlir or mlir without explicitly adding their import path to sys.path...

**Comment by stellaraccident** [comment]
Without seeing any details (like what is in the directory), it appears that at least the torch part of the project didn't build: the missing import is just a python file that should be symlinked into the build tree -- that's not even the native library, so no funny business: just python.

Look closely at the cmake output and make sure it is enabling the torch integration when it builds.

**Comment by stellaraccident** [comment]
Sorry to be pedantic, but did you *export* the PYTHONPATH or just set it? It looks like python isn't seeing the env var.

**Comment by hunbssfy** [comment]
You were right I didn't export the PYTHONPATH. Thanks!

About the test results though are those 'Expectedly Failed' tests supposed to fail at the moment?

**Comment by stellaraccident** [comment]
https://llvm.org/docs/TestingGuide.html#constraining-test-execution

It is a standard way in llvm to Mark a test that is known to be failing or not yet supported in some configuration.

**Comment by silvasean** [comment]
Hi @hunbssfy , I'm really sorry about the difficulty here. I recently ran into this exact same PYTHONPATH export issue when hooking up the CI and addressed it in https://github.com/llvm/mlir-npcomp/commit/ef118eb1e12797ea55ea3f89a9411ad44d4f848b

Just running torchscript_e2e_test.sh should now "just work" even if you don't have your PYTHONPATH exported.

**Comment by hunbssfy** [comment]
@silvasean Thanks for the correction! It works now.

**Comment by hunbssfy** [comment]
@silvasean , I have another question:
I am trying to invoke the example scripts under `frontend/pytorch/examples`, now this one:
`# -*- Python -*-
# This file is licensed under a pytorch-style license
# See frontends/pytorch/LICENSE for license information.

import torch
import torch_mlir

import npcomp
from npcomp.compiler.pytorch.backend import refjit, frontend_lowering
from npcomp.compiler.utils import logging

import test_utils

logging.enable()

torch.manual_seed(0)
input = torch.rand(2, 3)

mb = torch_mlir.ModuleBuilder()
with mb.capture_function("cos", [input]) as f:
  result = torch.cos(input)
  f.returns([result])

backend = iree.IreeNpcompBackend()
jit_module = backend.load(backend.compile(frontend_lowering.lower_module(mb.module)))

logging.debug(f"Executing jit_module.cos")
test_utils.compare_outputs(torch.cos, jit_module.cos, input)

# This fails because ModuleBuilder represents torch.cos with a constant:
#   https://github.com/llvm/mlir-npcomp/issues/135
test_utils.compare_outputs(torch.cos, jit_module.cos, input + 1)`

But I got "iree is not defined" error, 
![image](https://user-images.githubusercontent.com/6930027/125254377-fb5a5700-e32c-11eb-9ded-a7a61ef82248.png)

I imported iree with `import iree` but got another error:
![image](https://user-images.githubusercontent.com/6930027/125254503-17f68f00-e32d-11eb-9a4b-454da5327854.png)

I installed iree with this command:
`pip3 install iree-compiler-snapshot iree-runtime-snapshot -f https://github.com/google/iree/releases
`
are there any steps I am missing here?
