### ISSUE TITLE
Error when building npcomp in docker

### ISSUE THREAD

**Issue by hunbssfy** [llvm/mlir-npcomp#266]
There are two problems I ran into today after fetching the latest code:

1. When I run `cmake --build /build/npcomp --target check-npcomp check-frontends-pytorch
` in docker environment following README.md in the top directory, I got:
![image](https://user-images.githubusercontent.com/6930027/127985888-abf9df78-d425-4ebc-99ee-c7e16242491c.png)
This used to work and there used to be directories under `/build` such as `llvm-install,llvm-build, npcomp`. Now there is only `/build/npcomp` and the directory is almost empty except a .env file and few newly created directories. 

I noticed some changes in the build process in https://github.com/llvm/mlir-npcomp/pull/251 and https://github.com/llvm/mlir-npcomp/pull/258. Could someone update this README file to point it to the correct build output directory? 

2. The second problem is probably related to the first: `tools/torchscript_e2e_test.sh --config=iree
`  this command will show that it cannot find the corresponding test package:
![image](https://user-images.githubusercontent.com/6930027/127986878-e4869b34-09ef-4e5f-b320-2d126779cb7f.png)

Thanks!

**Comment by silvasean** [comment]
I just refreshed the instructions: https://github.com/llvm/mlir-npcomp/commit/a153cf4ef26216590a95cad5d5600bbbd5e0dda5

Can you give them a try? If not, can you include the full logs with the errors?

**Comment by hunbssfy** [comment]
@silvasean 
Hi, I just tried the newest commit and both commands seem to go through. Although I am running a custom-built IREE and e2e test failed, I'll have a look at the tests myself, Thanks!

**Comment by hunbssfy** [comment]
Hi @silvasean,

About the failed tests yesterday... I started a fresh docker and built npcomp, I installed iree (not my custom built one) via pip. But the tests still failed:

![image](https://user-images.githubusercontent.com/6930027/128286832-62b29b6a-7078-45f4-a88d-cfb1327ca774.png)

Maybe the newest commits caused this?

**Comment by cathyzhyi** [comment]
Currently IREE backend is failing because their llvm version is older and doesn't match the one used by NPCOMP.  If you add -v you will see the failure is because `builtin.module` can't be recognized. The op is the result of recent MLIR refactoring and the older MLIR  used by IREE is not aware of this op.

**Comment by silvasean** [comment]
The latest IREE has the fix for builtin.module. This is the current list I see locally (will update xfail sets soon)

```
PASS - "MmModule_basic"
PASS - "MmModule_chained"
PASS - "MmDagModule_basic"
PASS - "MmTanhModule_basic"
PASS - "AdaptiveAvgPool2dModule_basic"
PASS - "FlattenStaticModule_basic"
PASS - "FlattenRank0Module_basic"
XFAIL - "FlattenDynamicModule_basic"
XFAIL - "MaxPool2dModule_basic"
XPASS - "ResNet18Module_basic"
PASS - "Mlp1LayerModule_basic"
PASS - "Mlp2LayerModule_basic"
PASS - "Conv2dNoPaddingModule_basic"
FAIL - "Conv2dWithPaddingModule_basic"
XFAIL - "Conv2dWithPaddingDilationStrideModule_basic"
PASS - "BatchNorm1DModule_basic"
PASS - "BatchNorm2DModule_basic"
PASS - "BatchNorm3DModule_basic"
XFAIL - "QuantizedMLP_basic"
PASS - "ElementwiseUnaryModule_basic"
PASS - "ElementwiseBinaryModule_basic"
PASS - "ElementwiseTernaryModule_basic"
PASS - "ElementwiseAddModule_basic"
PASS - "ElementwiseUnsqueezeBroadcastModule_basic"
PASS - "ElementwiseFlattenBroadcastModule_basic"
PASS - "ElementwiseReluModule_basic"
```

**Comment by cathyzhyi** [comment]
Ha, seems `ResNet18Module_basic` passed with IREE as well?

**Comment by silvasean** [comment]
yep :)

**Comment by hunbssfy** [comment]
@silvasean Do you know which patch in iree fix the builtin.module issue?
![image](https://user-images.githubusercontent.com/6930027/130392699-ce5ba3ec-45c5-4fbd-b30e-e0f84386612d.png)

**Comment by stellaraccident** [comment]
It's an asm format change from upstream. It will have come in via an iree submodule bump. We don't track such unstable changes between releases.

**Comment by hunbssfy** [comment]
@stellaraccident Thanks, I'll just update upstream version directly.
