### ISSUE TITLE
Resnet 18 iree path

### ISSUE THREAD

**Issue by hunbssfy** [llvm/mlir-npcomp#280]
Hello,
I substituted refjit backend with iree backend in torchscript_resnet18_e2e.py:
```
backend = iree.IreeNpcompBackend()
#backend = refjit.RefjitNpcompBackend()
```
I know this probably won't run successfully ... But worth a try, I got this error:
![image](https://user-images.githubusercontent.com/6930027/129540578-f935da78-38e9-4f79-a213-a3d9e2db2395.png)

I also ran the iree-translate command alone (I copied the instruction from the last line of the screenshot above, I also dumped the input file using `mb.module.operation.get_asm` and `f.write` and then passed the input file as iree-translate's parameter):
![image](https://user-images.githubusercontent.com/6930027/129540856-db63d65d-c297-43fa-a169-fa2f43acee8c.png)

My questions are:
1. Are these two errors caused by the same reason but just different print-out or am I invoking the iree-translate tool the wrong way?
2. Since I am not very familiar with iree (as well as MLIR since I am still studying it:)), how to debug this kind of problem in general?
3. Is there any plan to pass the resnet18 test with iree backend?

Thanks in advance to anyone who helps me with these questions!

**Comment by silvasean** [comment]
Can you try using the latest IREE? The first error is a known error that was fixed recently. Not sure about the second.

**Comment by silvasean** [comment]
I just ran into the hal.constant_pool.load issue myself. It was pointing at an opaque constant dumped by the reproducer. Do you have large_elements_limit on your get_asm call? If you do, then removing it should fix the issue.

I will try to make IREE give a better diagnostic for this.

**Comment by hunbssfy** [comment]
Hello Sean, Thanks for the answer!

I upgraded to the latest iree-runtime-snapshot and iree-compiler-snapshot from https://github.com/google/iree/releases/tag/snapshot-20210816.466 and the first error is gone. Could you point me to the patch which fixed this problem so that I can merge it into my custom iree project?

As for the second error, I also changed to the lastest iree snapshot and I dropped the `large_elements_limit` option in my `get_asm` call:
![image](https://user-images.githubusercontent.com/6930027/129656498-715f4a0a-1231-4ba3-8e18-24822009b808.png)
but the error still exists with a slightly different error message:
![image](https://user-images.githubusercontent.com/6930027/129660334-024e2954-bedd-49c3-9e2d-e70e42ec09a9.png)

**Comment by silvasean** [comment]
The first error was fixed by https://github.com/google/iree/issues/6629

For debugging the second, can you file an IREE bug with appropriate starting IR and iree-translate command to reproduce? I don't think this is npcomp-specific. (feel free to add me on that bug, I work actively with IREE as well)

btw, I'll be on vacation for the next week, but I'll respond right as I get back

**Comment by hunbssfy** [comment]
Sure, Thanks!
