### ISSUE TITLE
Re-layout torch_mlir Python packages

### ISSUE THREAD

**Issue by stellaraccident** [llvm/mlir-npcomp#311]
I think we have a bit more cleanup to do of the python namespaces to get them in better shape. Just dumping issues I see here:

* Let's claim the top-level `torch_mlir` namespace and put everything in there:
  * `torch_mlir.dialects.torch`
  * `torch_mlir.dialects.torch.importer.fx` <-- New stuff Ramiro is working on
  * `torch_mlir.dialects.torch.importer.torch_ir` <-- Python bits currently directly under `torch_mlir`
  * `torch_mlir._mlir_libs._torchIRPlugin` <-- Current native library `_torch_mlir`
* Can keep `torch_mlir_utils` as-is for now since it seems to just be development tooling.

Note specifically that laying out the native libraries this way will help down the road with RPath issues and such.

We should then have a CMake variable `-DBUILD_TORCH_MLIR_PLUGIN=1` which enables the packages:
* `torch_mlir.dialects.torch.importer.torch_ir` 
* `torch_mlir._mlir_libs._torchIRPlugin`

The wheels we distribute would build and claim this top-level `torch_mlir` namespace. Others who want to include the ability to import from PyTorch in another compiler can then alias the above into their own compiler namesapce (i.e. `foo_compiler.dialects.torch`...) and have everything layer properly and not name collide. This kind of namespacing is the current way I have set up newer projects.

Other nits:
* `.dialects.torch.register_torch_dialect` -> `register_dialect`. Can also create a native submodule for it and import * like I do in IREE: https://github.com/google/iree/blob/080cbc466214c698bf6086d7bc1fc205ade2706c/llvm-external-projects/iree-dialects/python/mlir/dialects/iree.py#L8
* If laying out this way, the importers can all use relative imports and be fully relocatable/embeddable into other compilers.
* We currently declare the directory tree under `torch-mlir/python/mlir`. This followed some early copy-pasta from upstream. Projects that own a namespace should base it on their namespace (i.e. `torch-mlir/python/torch_mlir`), which alleviates development confusion and makes it less likely to mix and match the wrong namespaces.

**Comment by stellaraccident** [comment]
Sorry for the churn on this: it took a bit of iteration to get a feel for how all of these namespaces can fit together, especially across projects, etc.

**Comment by stellaraccident** [comment]
Also we should fix the design issue noted here upstream: https://github.com/llvm/mlir-npcomp/blob/c24ca5d6398f246a82c25e8cd4ca461a58b29182/external/torch-mlir/python/CMakeLists.txt#L44

Not only will it make the binaries smaller, but I estimate that it will reduce the number of files to compile to ~low hundreds, putting this firmly in the realm of something that is not *that* onerous to distribute as a source package and expect people to actually build it (which will likely be important when considering different Torch binary versions, etc).

**Comment by silvasean** [comment]
Thanks stella. will get on this asap
