### ISSUE TITLE
Enable CI for PyTorch frontend

### ISSUE THREAD

**Issue by stellaraccident** [llvm/mlir-npcomp#48]
The instructions in the README and docker image are now up to date. It would be nice to get the CI going for it. I'm not entirely certain how to adapt the LLVM install caching to building within a container.

We might want to wait too until we get closer to PyTorch head: I suspect we'll be successful then at just installing an appropriate version and building against it (and can forgo the container in the CI).

**Comment by powderluv** [comment]
Fixed in https://github.com/llvm/mlir-npcomp/pull/166
